version: '3.6'

services:

  # WEBAPI MONGODB
  tagsapi:
    image: tagsapi
    build:
      context: ./TagsApi
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010;
    ports:
      - '5010:5010'
    expose:
      - '5010'