version: '3.6'

services:

  ################### REST API
  tagsapi:
    image: tagsapi
    build:
      context: ./TagsApi
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010;
    ports:
      - '5010:5010'
    expose:
      - '5010'

  ################### GATEWAY GQL
  # gqlgateway:
  #   image: ${DOCKER_REGISTRY-}gqlgateway
  #   build:
  #     context: .
  #     dockerfile: src/GqlGateway/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Release
  #     - ASPNETCORE_URLS=http://+:5000;
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - neo4jgql
  #     - tagswebapi
  #     - redis

  ################### NEO4J GQL
  # neo4jgql:
  #   build:
  #     context: .
  #     dockerfile: src/Neo4jGql/Dockerfile
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=s3cr3t
  #     - NEO4J_URI=neo4j://neo4jdb:7687
  #     - NODE_ENV=development