version: '3.6'
services:
  gqlgateway:
    image: ${DOCKER_REGISTRY-}gqlgateway
    build:
      context: .
      dockerfile: GqlGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000;
    ports:
      - "5000:5000"
    depends_on:
      - tagswebapi
      - redis
  tagswebapi:
    image: ${DOCKER_REGISTRY-}tagswebapi
    build:
      context: .
      dockerfile: TagsWebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003;
    ports:
      - "5003:5003"
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1433:1433'
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
